version: '3.8'

services:
  quickchart:
    image: ianw/quickchart:v1.8.1
    container_name: quickchart
    ports:
      - "3400:3400"
    environment:
      - DISABLE_SANDBOX=true
    restart: unless-stopped
